name: time_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.2.1
  moor_flutter: ^2.0.0
  dartz: ^0.8.9
  flutter_slidable: ^0.5.4
  mobx: ^0.4.0+1
  flutter_mobx: ^0.3.6
  provider: ^4.0.2
  flutter_material_color_picker: ^1.0.5
  audioplayers: ^0.14.0
  wakelock: ^0.1.3+4
  simple_animations: ^1.3.6

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  auto_route_generator: ^0.2.1
  moor_generator: ^2.2.0
  mobx_codegen: ^0.4.1
  mockito: ^4.1.1


flutter:
  uses-material-design: true

  assets:
    - lang/en.json
    - lang/ru.json
    - assets/audio/

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/Fira_Sans/FiraSans-Regular.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-Light.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-LightItalic.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraLight.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-ExtraLightItalic.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-Medium.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-MediumItalic.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-SemiBold.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-SemiBoldItalic.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-Black.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-BlackItalic.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-Bold.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-BoldItalic.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-Thin.ttf
        - asset: assets/fonts/Fira_Sans/FiraSans-ThinItalic.ttf
    
    - family:  AppIcons
      fonts:
      - asset: assets/fonts/AppIcons.ttf