name: time_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.2.1
  moor_flutter: ^2.0.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  auto_route_generator: ^0.2.1
  moor_generator: ^2.2.0


flutter:

  uses-material-design: true